"""Generate ``cyqnt_trd/standard_bot/data/DATA_API.md`` from the data catalog.

``BLOCKS_API.md`` is the ground truth a codegen LLM reads for compute nodes.
This produces its counterpart for ``type: data`` nodes, so a codegen prompt can
inject ``{{DATA_API}}`` exactly the way it injects ``{{BLOCKS_API}}``.

The doc is generated, never hand-edited: the callable surface
(``runtime/data.py``), the Canvas param forms and this file all come from
:mod:`cyqnt_trd.standard_bot.data.catalog`, so they cannot drift.

    python docs/gen_data_api.py [--check]

``--check`` regenerates in memory and exits non-zero if the committed file is
stale, so CI can catch a catalog change that forgot to refresh the doc.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from cyqnt_trd.standard_bot.data.catalog import (  # noqa: E402
    Availability,
    DataNodeSpec,
    SourcePath,
    list_nodes,
)

OUTPUT = REPO_ROOT / "cyqnt_trd" / "standard_bot" / "data" / "DATA_API.md"

_AVAILABILITY_BLURB = {
    Availability.BACKTESTABLE: "real history, deep enough to walk forward",
    Availability.SEMI: "history exists but is windowed / shallow / publication-lagged",
    Availability.FORWARD_ONLY: "snapshot only — no replayable history; collect forward",
    Availability.EXTERNAL_PENDING: "contract specified, feed not onboarded",
    Availability.NOT_WIRED: "no endpoint exists anywhere",
}

_SOURCE_BLURB = {
    SourcePath.INDICATORS_API: "Technical Indicator API (base URL from `$INDICATORS_URL`)",
    SourcePath.BDP_SCREENING: 'bdp screening (`source:"bdp"` condition clause)',
    SourcePath.PUBLIC_BINANCE: "public Binance (`api`/`fapi`/`data-api.binance.vision`) or `alternative.me`",
    SourcePath.SQUARE_SKILL: "Binance Square skill API (Prod IP-whitelisted)",
    SourcePath.INTERNAL_HTTP: "internal-network HTTP endpoint (host and route come from the private deployment config, not from this repo)",
    SourcePath.LOCAL_PARQUET: "local parquet under a `--*-dir` root",
    SourcePath.EXTERNAL_VENDOR: "third-party vendor feed (外采)",
}

_GROUPS = [
    ("Kline / technical", ("C",)),
    ("Derivatives / crowding", ("D", "A", "N")),
    ("Orderbook / microstructure", ("O",)),
    ("News / event", ("E",)),
    ("Social / attention", ("S",)),
    ("Cross-section / universe", ("L", "P")),
    ("Flow / whale", ("F",)),
    ("Regime / macro / cross-asset", ("R",)),
    ("Account", ("*",)),
]


def _fence(text: str) -> str:
    return "`%s`" % text


def _params_table(spec: DataNodeSpec) -> List[str]:
    if not spec.params:
        return ["_(no parameters)_", ""]
    lines = [
        "| param | type | required | default | notes |",
        "|---|---|---|---|---|",
    ]
    for item in spec.params:
        default = "" if item.default is None else _fence(repr(item.default))
        note = item.description
        if item.options:
            note = ("%s (%s)" % (note, " / ".join(_fence(str(o)) for o in item.options))).strip()
        if item.source:
            note = ("%s — must reference an upstream node output" % note).strip(" —")
        lines.append(
            "| %s | %s | %s | %s | %s |"
            % (_fence(item.key), _fence(item.type), "yes" if item.required else "no", default, note)
        )
    lines.append("")
    return lines


def _node_section(spec: DataNodeSpec) -> List[str]:
    lines: List[str] = []
    lines.append("### `data.%s`" % spec.name)
    lines.append("")
    lines.append(spec.description)
    lines.append("")
    lines.append(
        "- **availability**: `%s` — %s"
        % (spec.availability.value, _AVAILABILITY_BLURB[spec.availability])
    )
    lines.append("- **source**: %s" % _SOURCE_BLURB[spec.source_path])
    if spec.endpoint:
        lines.append("- **endpoint**: %s" % spec.endpoint)
    if spec.substitute:
        lines.append("- **substitute**: %s" % spec.substitute)
    returns = spec.returns
    ret = "- **returns**: `%s` — %s" % (returns.type, returns.description)
    if returns.columns:
        ret += " · columns: %s" % ", ".join(_fence(c) for c in returns.columns)
    lines.append(ret)
    if spec.pit_hazard:
        lines.append("- **⚠️ PIT hazard**: %s" % spec.pit_hazard)
    if spec.notes:
        lines.append("- **note**: %s" % spec.notes)
    lines.append("")
    lines.extend(_params_table(spec))
    return lines


def render() -> str:
    nodes = list_nodes()
    by_name = {node.name: node for node in nodes}
    assigned: set = set()

    lines: List[str] = []
    lines.append("# `data.*` — Strategy Spec Data-Node API Reference")
    lines.append("")
    lines.append("> Generated by `docs/gen_data_api.py` from")
    lines.append("> `cyqnt_trd/standard_bot/data/catalog.py`. **Do not hand-edit.**")
    lines.append("")
    lines.append(
        "The counterpart to `cyqnt_trd/blocks/BLOCKS_API.md`. `BLOCKS_API.md` documents the "
        "*compute* nodes (`indicators` / `conditions` / `entry` / …); this documents the "
        "*data* nodes a spec addresses as `type: data, function: <name>`."
    )
    lines.append("")
    lines.append("```python")
    lines.append("from cyqnt_trd.standard_bot.runtime import data, action")
    lines.append("")
    lines.append('klines_1h = data.klines(symbol="BTCUSDT", interval="1h", limit=500)')
    lines.append('funding   = data.funding(symbol="BTCUSDT", limit=500)')
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Read this before choosing a node")
    lines.append("")
    lines.append(
        "**Availability is not a footnote — it decides whether your strategy can be "
        "backtested at all.** Most internal snapshot endpoints (Square social, "
        "futuresRadar, movement) are Redis-TTL reads with no point-in-time history. "
        "Replaying one reuses *today's* value at every historical bar, which produces a "
        "confident and completely fictional equity curve."
    )
    lines.append("")
    lines.append("| tier | meaning | allowed in backtest |")
    lines.append("|---|---|---|")
    for tier in (
        Availability.BACKTESTABLE,
        Availability.SEMI,
        Availability.FORWARD_ONLY,
        Availability.EXTERNAL_PENDING,
        Availability.NOT_WIRED,
    ):
        allowed = {
            Availability.BACKTESTABLE: "yes",
            Availability.SEMI: "only within the available window — check the first timestamp",
            Availability.FORWARD_ONLY: "no — live/paper only, strategy is RESEARCH_ONLY",
            Availability.EXTERNAL_PENDING: "no — feed not onboarded",
            Availability.NOT_WIRED: "no",
        }[tier]
        lines.append("| `%s` | %s | %s |" % (tier.value, _AVAILABILITY_BLURB[tier], allowed))
    lines.append("")
    lines.append(
        "`data.validate_nodes([...], for_backtest=True)` enforces this at compile time "
        "and quotes the specific hazard, so the failure lands before the run rather than "
        "as a flat curve after it."
    )
    lines.append("")
    lines.append("**An empty result is not `ok`.** The Square APIs are Prod IP-whitelisted and "
                 "answer off-whitelist calls with `success: true` and an empty body — "
                 "indistinguishable from \"nothing happened\" unless the status is carried "
                 "separately. Every call routes through the catalog, which grades an empty "
                 "frame as `degraded`, never as zero.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # summary index
    lines.append("## Index")
    lines.append("")
    lines.append("| node | strategy types | availability | source |")
    lines.append("|---|---|---|---|")
    for spec in sorted(nodes, key=lambda n: n.name):
        lines.append(
            "| `data.%s` | %s | `%s` | %s |"
            % (
                spec.name,
                " ".join(spec.strategy_types),
                spec.availability.value,
                spec.source_path.value,
            )
        )
    lines.append("")
    lines.append("---")
    lines.append("")

    for title, types in _GROUPS:
        group = [
            node
            for node in nodes
            if node.name not in assigned and any(t in node.strategy_types for t in types)
        ]
        if not group:
            continue
        lines.append("## %s" % title)
        lines.append("")
        for spec in group:
            assigned.add(spec.name)
            lines.extend(_node_section(spec))
        lines.append("---")
        lines.append("")

    leftovers = [node for node in nodes if node.name not in assigned]
    if leftovers:
        lines.append("## Other")
        lines.append("")
        for spec in leftovers:
            lines.extend(_node_section(spec))
        lines.append("---")
        lines.append("")

    lines.append("## Codegen contract")
    lines.append("")
    lines.append("- Call form is `data.<function>(**params)` — the same one-rule derivation the")
    lines.append("  compute nodes use, so no mapping table is needed.")
    lines.append("- `import` line: `from cyqnt_trd.standard_bot.runtime import data, action`.")
    lines.append("- Param keys above are exactly the spec `params[].key` values.")
    lines.append("- Wrap a whole decision cycle in `with data.session() as s:` so every node in")
    lines.append("  the DAG shares one `as_of`; `s.status_map()` then feeds")
    lines.append("  `SnapshotMeta.source_status` and `s.warnings()` feeds `SnapshotMeta.warnings`.")
    lines.append("- A failed fetch raises `data.DataUnavailable`; `data.collect([...])` degrades")
    lines.append("  instead, returning the frames it got plus the per-node status.")
    lines.append("")
    counts = {tier: 0 for tier in Availability}
    for spec in nodes:
        counts[spec.availability] += 1
    lines.append(
        "_%d nodes: %s._"
        % (
            len(nodes),
            ", ".join(
                "%d %s" % (counts[tier], tier.value) for tier in Availability if counts[tier]
            ),
        )
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if the committed file is stale"
    )
    args = parser.parse_args()

    content = render()
    if args.check:
        if not OUTPUT.exists():
            print("DATA_API.md missing; run: python docs/gen_data_api.py", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != content:
            print(
                "DATA_API.md is stale (catalog changed); run: python docs/gen_data_api.py",
                file=sys.stderr,
            )
            return 1
        print("DATA_API.md up to date")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print("wrote %s (%d lines)" % (OUTPUT, content.count("\n") + 1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
