"""
Signal layer exports for the standard bot architecture.
"""

from .encoders import EncodedCloseSeries, encode_close_series, series_for
from .interfaces import (
    BatchSignalPlugin,
    IncrementalSignalPlugin,
    SignalComposer,
    SignalPlugin,
    SignalState,
    StepSignalResult,
)
from .plugins import (
    AdxTrendStrengthConfig,
    AdxTrendStrengthPlugin,
    AtrBreakoutConfig,
    AtrBreakoutPlugin,
    BollingerMeanReversionConfig,
    BollingerMeanReversionPlugin,
    DonchianBreakoutConfig,
    DonchianBreakoutPlugin,
    LiquidationReversalConfig,
    LiquidationReversalPlugin,
    MacdTrendFollowConfig,
    MacdTrendFollowPlugin,
    MovingAverageCrossConfig,
    MovingAverageCrossPlugin,
    MultiTimeframeMaSpreadConfig,
    MultiTimeframeMaSpreadPlugin,
    OiFundingBreakoutConfig,
    OiFundingBreakoutPlugin,
    PriceMovingAverageConfig,
    PriceMovingAveragePlugin,
    RsiReversionConfig,
    RsiReversionPlugin,
    register_builtin_plugins,
)
from .registry import PipelineStepResult, SignalPluginRegistry

__all__ = [
    "AdxTrendStrengthConfig",
    "AdxTrendStrengthPlugin",
    "AtrBreakoutConfig",
    "AtrBreakoutPlugin",
    "BatchSignalPlugin",
    "BollingerMeanReversionConfig",
    "BollingerMeanReversionPlugin",
    "DonchianBreakoutConfig",
    "DonchianBreakoutPlugin",
    "EncodedCloseSeries",
    "IncrementalSignalPlugin",
    "LiquidationReversalConfig",
    "LiquidationReversalPlugin",
    "MacdTrendFollowConfig",
    "MacdTrendFollowPlugin",
    "MovingAverageCrossConfig",
    "MovingAverageCrossPlugin",
    "MultiTimeframeMaSpreadConfig",
    "MultiTimeframeMaSpreadPlugin",
    "OiFundingBreakoutConfig",
    "OiFundingBreakoutPlugin",
    "PipelineStepResult",
    "PriceMovingAverageConfig",
    "PriceMovingAveragePlugin",
    "RsiReversionConfig",
    "RsiReversionPlugin",
    "SignalComposer",
    "SignalPlugin",
    "SignalPluginRegistry",
    "SignalState",
    "StepSignalResult",
    "encode_close_series",
    "register_builtin_plugins",
    "series_for",
]
